### ISSUE TITLE
ability to add directional arrows

### ISSUE THREAD

**Issue by devmondo** [s-yadav/patternLock#5]
hi,
lovely work there :)  can we emulate this picture here where arrows point to direction
http://www.google.ae/imgres?imgurl=http://media.idownloadblog.com/wp-content/uploads/2014/01/AndroidLock-iOS-7.png&imgrefurl=http://www.idownloadblog.com/2014/01/11/how-to-theme-the-lock-screen-on-ios-7/&h=525&w=593&tbnid=Gkvwl28zxLlAVM:&zoom=1&docid=NUvvFXXKuiYUsM&ei=QFWUVYrlBoehsAHGpLfoCg&tbm=isch&ved=0CCIQMygIMAg

thanks in advanced.

**Comment by s-yadav** [comment]
Hi devmondo, 
Its not added to the plugin core till now, I am planning to add class defining the direction on lines and circle, so that any kind of theming can be done through css.

**Comment by devmondo** [comment]
thanks man for reply, please do it as fast as you can, the customization is preventing me from adding to multiple projects, great work again and all the best :)

**Comment by s-yadav** [comment]
Check for latest commit, added directional classes (n,s,w,e,n-e,n-w,s-e,s-w) where n,s,e,w signifies north, south, east, west.
For your requirement a rough css can be,
```css
.patt-circ.hovered .patt-dots{
    display: none;
}

.patt-circ.e{
    background-color: #fff;
    background-image: url('left-arrow.png');
    background-position: center;
}

.patt-circ.s{
    background-color: #fff;
    background-image: url('down-arrow.png');
    background-position: center;
}
```
Adding a demo, and documentation may take some time. Till you can play around styling directional classes to meet your requirement.
